### ISSUE TITLE
skimage version should be under 0.16

### ISSUE THREAD

**Issue by Ziqi-Song** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#10]
skimage version should be < 0.16.

In src/models/SGRNet_model.py", line 20:
`from skimage.measure import compare_mse`
However,
![image](https://user-images.githubusercontent.com/25892528/148904927-c83ec677-a7ec-45a2-a86e-bdaa93fa44e7.png)

**Comment by hy-zpg** [comment]
you install scikit-image==0.17.2, this function still exists.
