### ISSUE TITLE
Google drive link missing for CompositionShadowGeneration-100

### ISSUE THREAD

**Issue by albertmundu** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#11]
Hello authors,
Please share the google drive link for the 100 real composite images (CompositionShadowGeneration-100). https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBA#visualization-results-on-real-composite-images
Thank you.

**Comment by hy-zpg** [comment]
Hi, the google drive link is updated, please refer to https://drive.google.com/drive/folders/1CspARS6nBVQhF0we-jro8N5PRnfTizxM?usp=sharing

**Comment by albertmundu** [comment]
Thank you @hy-zpg
