### ISSUE TITLE
Custom training

### ISSUE THREAD

**Issue by sumantha-NTS** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#14]
Hi,

Not able to train model with DESOBA dataset. Training script able to load selected options, but not able to create model file.

Below is the log file of train script 
----------------- Options ---------------
     adain_mask_generator: 0                             
                    angle: 60                            
               batch_size: 8                             	[default: 1]
                    beta1: 0.5                           
         bg_instance_path: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/DESOBA_DATASET//InstanceMask	[default: None]
        bg_instance_path1: None                          
         bg_maskattention: 0                             
         bg_selfattention: 0                             
           bg_shadow_path: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/DESOBA_DATASET//ShadowMask	[default: None]
          bg_shadow_path1: None                          
          checkpoints_dir: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/custom_model	[default: ./checkpoints]
               conditionD: 0.0                           
           continue_train: True                          	[default: False]
                 dataroot: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/DESOBA_DATASET/	[default: None]
                dataroot1: None                          
             dataset_mode: shadowparam                   	[default: aligned]
                direction: AtoB                          
              display_env: main                          
             display_freq: 100                           	[default: 4]
               display_id: 1                             
            display_ncols: 4                             
             display_port: 8002                          	[default: 8097]
           display_server: http://localhost/              	[default: http://localhost:8097/]
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 10                            	[default: 1]
                 fineSize: 256                           
               finetuning: False                         
           finetuning_dir: None                          
         finetuning_epoch: None                          
          finetuning_name: None                          
                  gpu_ids: 0                             
                grid_size: 4                             
             illumination: 0.0                           
                init_gain: 0.02                          
                init_type: xavier                        
                 input_nc: 3                             
            instance_path: None                          
           instance_path1: None                          
                  isTrain: True                          	[default: None]
               keep_ratio: False                         
               lambda_GAN: 0.1                           	[default: 0.0]
          lambda_GAN_mask: 0.0                           
                lambda_I1: 10.0                          	[default: 1]
                lambda_L1: 0.0                           
                lambda_M1: 10.0                          	[default: 1]
                lambda_P1: 1                             
              lambda_REF1: 1                             
              lambda_STN1: 1                             
               lambda_TV1: 1                             
                lambda_bd: 0.0                           
            lambda_smooth: 0.0                           
               light_path: None                          
              light_path1: None                          
           light_vis_path: None                          
          light_vis_path1: None                          
                 loadSize: 256                           	[default: 286]
                       lr: 0.0002                        
                     lr_D: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: lambda                        
                mask_test: None                          
               mask_train: None                          
         max_dataset_size: inf                           
                    model: SGRNet                        	[default: cycle_gan]
               n_layers_D: 3                             
                     name: SGRNet_GRESNEXT18_C32_Dpixel_lrD0.0002	[default: experiment_name]
                      ndf: 64                            
                     netD: pixel                         	[default: basic]
                     netG: RESNEXT18                     	[default: resnet_9blocks]
            new_mask_path: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/DESOBA_DATASET//shadownewmask	[default: None]
           new_mask_path1: None                          
                      ngf: 32                            	[default: 64]
                    niter: 100                           
              niter_decay: 300                           	[default: 100]
                  no_crop: True                          	[default: False]
               no_dropout: False                         
                  no_flip: True                          	[default: False]
                  no_html: False                         
                 no_lsgan: True                          
                no_rotate: True                          	[default: False]
                     norm: instance                      	[default: batch]
                norm_mean: [0.5, 0.5, 0.5]               
                 norm_std: [0.5, 0.5, 0.5]               
              num_threads: 4                             
                output_nc: 3                             
               param_path: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/DESOBA_DATASET//SOBA_params	[default: None]
              param_path1: None                          
                    phase: train                         
                pool_size: 0                             
               print_freq: 100                           
               randomSize: False                         
              redark_path: None                          
             redark_path1: None                          
                 residual: 0.0                           
           resize_or_crop: resize_and_crop               
          save_epoch_freq: 1                             	[default: 5]
         save_latest_freq: 5000                          
           serial_batches: False                         
          shadowfree_path: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/DESOBA_DATASET//DeshadowedImage	[default: None]
         shadowfree_path1: None                          
           shadowimg_path: /content/drive/MyDrive/POCs/MaskRCNN_POC/shadow_extract/Generate_Shadow_script/Object-Shadow-Generation-Dataset-DESOBA/DESOBA_DATASET//ShadowImage	[default: None]
          shadowimg_path1: None                          
          shadowmask_path: None                          
         shadowmask_path1: None                          
               span_range: 0.9                           
           stn_model_type: unbounded_stn                 
                   suffix:                               
         update_html_freq: 10000                         
             use_our_mask: False                         
                  verbose: True                          	[default: False]
                   warp_N: 1                             
                wdataroot: None                          
----------------- End -------------------
^C

**Comment by hy-zpg** [comment]
loading data is time-consuming, you can wait for a moment until the print log of 'dataset is 35000' on your screen.
