### ISSUE TITLE
合成的阴影

### ISSUE THREAD

**Issue by xjsxjs** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#19]
请问谷歌云盘里的预训练模型是可用的吗，我加载到自己的图像时，每张图像都没法产生阴影，请问如何解决呀，谢谢
这是原图
![17](https://user-images.githubusercontent.com/84959251/188870375-b9806868-769d-41f8-aaf6-cfd8cbba458a.png)
这是通过运行pix2pix_realcomposite.sh之后的效果
![17](https://user-images.githubusercontent.com/84959251/188870449-262dd20d-723b-4c5b-98bb-31e181dea16a.png)
是我哪一步做错了吗，期待您的回复

**Comment by hy-zpg** [comment]
Hi, pix2pix_realcomposite.sh means that using pix2pix baseline model to predict shadow, the performance of the pix2pix model is actually  poor, you can run SGRNet_realcomposite.sh for a try.
