### ISSUE TITLE
How do you calculate linear transformation parameters?

### ISSUE THREAD

**Issue by UdonDa** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#2]
Hi, @ustcnewly .

I read your paper and think that your work can bring the future direction to shadow generation research!

I have a question about your method about
```
Given paired images {Ic, Ig}, the ground-truth shadow parameter {w_{dark}, b_{dark}} for the foreground shadow can be easily calculated by using linear regression.
```

How do you calculate a linear regression?
Would you explain this question?

Best regards.

**Comment by hy-zpg** [comment]
The linear regression is calculated according to the Eqn. (6) in our paper. Specifically, we calculate the linear regression based on the tuple {Ic, Ig, Mfs}, related code please refer the link [https://github.com/cvlab-stonybrook/SID/blob/main/data_processing/compute_params.py].

**Comment by UdonDa** [comment]
Hi, @hy-zpg 
Thank you for replying!
I can produce such parameters.
Thank you.
