### ISSUE TITLE
Error with DesobaSyntheticImageGeneration_dataset.py 

### ISSUE THREAD

**Issue by tanmayj2020** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#5]
In the for loop when we do continue for i!=1 or i!=2 the logic seems not correct to me , can you have a look at the entire script

**Comment by hy-zpg** [comment]
When you have downloaded DESOBA dataset, you should set the correct path of DESOBA dataset. In detail,  python Vis_Desoba_Dataset.py to generate BOS Object shadow pairs  --shadowimg_path ./ShadowImage  --shadowfree_path ./DeshadowedImage  --instance_path ./InstanceMask  --shadow_path ./ShadowMask

**Comment by maixxq** [comment]
thanks for your work! how can we test with own data?
