### ISSUE TITLE
SGRNet 模型是否已发布，我没有找到，期待您的回复

### ISSUE THREAD

**Issue by zhanghongyong123456** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#6]
![image](https://user-images.githubusercontent.com/48466610/147178273-3871e8a5-3fca-4bcd-ad8a-99846a7de8ab.png)
没有链接

**Comment by hy-zpg** [comment]
您好，这边还没有完整放出来，1月初会完成所有代码模型整理。

**Comment by zhanghongyong123456** [comment]
> 你好，这个还没有完整放出来，1月初会完成所有代码模型整理。
好的，期待您的伟大作品，
