### ISSUE TITLE
关于requirement.txt  文件输出格式是否有一些问题

### ISSUE THREAD

**Issue by zhanghongyong123456** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#8]
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1601658315997/work
imageio @ file:///tmp/build/80754af9/imageio_1594161405741/work 
...
我安装时候出现
ERROR: Could not install packages due to an OSError: [Errno 2] 没有那个文件或目录: '/tmp/build/80754af9/dask-core_1602083700509/work'

这些有特定版本要求吗

**Comment by hy-zpg** [comment]
没有特殊要求，我已经更新了requirement.txt，主要保持torch版本就行。

**Comment by zhanghongyong123456** [comment]
> 没有特殊要求，我已经更新了requirement.txt，主要保持torch版本就行。

您好 ，pytorch必须1.6吗，我的机器是3090 的不支持10.2cuda，所以不能安装pytorch1.6，可否更换为1.7、1.8或者是1.9的pytorch版本
